import React from 'react';
import UserLayout from "@/Layout/UserLayout.jsx";

import {Input, Card, CardHeader, CardBody, CardFooter, Image, Button} from "@nextui-org/react";
import BerandaHero from "@/Pages/User/Beranda/BerandaHero.jsx";
import BerandaNavigation from "@/Pages/User/Beranda/BerandaNavigation.jsx";
import BerandaAccordion from "@/Pages/User/Beranda/BerandaAccordion.jsx";
import BerandaArtikel from "@/Pages/User/Beranda/BerandaArtikel.jsx";
import BerandaMateri from "@/Pages/User/Beranda/BerandaMateri";
import {Head} from "@inertiajs/react";
import BerandaInformasi from './BerandaInformasi';
import BerandaMultimedia from './BerandaMultimedia';
import BerandaFaq from './BerandaFaq';

const BerandaMain = () => {
    return (
        <>
            <Head>
                <title>Beranda - Sociesmedia</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <UserLayout>
                <BerandaHero/>
                <BerandaNavigation/>
                {/* <BerandaInformasi/> */}
                <BerandaMultimedia/>
                <BerandaMateri/>
                <BerandaArtikel/>
                <BerandaFaq/>
            {/*<BerandaAccordion/>*/}
        </UserLayout>
        </>
    );
};

export default BerandaMain;
