import React from 'react';
import UserLayout from "@/Layout/UserLayout.jsx";

import {Input, Card, CardHeader, CardBody, CardFooter, Image, Button} from "@nextui-org/react";
import BerandaHero from "@/Pages/User/Beranda/BerandaHero.jsx";
import {Head} from "@inertiajs/react";
import PenelitiHero from './PenelitiHero';
import PenelitiProfile from './PenelitiProfile';


const PenelitiMain = () => {
    return (
        <>
            <Head>
                <title>Peneliti - Sociesmedia</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <UserLayout>
                <PenelitiHero/>
                <PenelitiProfile/>
        </UserLayout>
        </>
    );
};

export default PenelitiMain;
