import React from 'react';
import UserLayout from "@/Layout/UserLayout.jsx";
import { Button } from "@/Components/ui/button.jsx"
import {Head} from "@inertiajs/react";
import MultimediaHero from "@/Pages/User/Multimedia/MultimediaHero.jsx";
import MultimediaPilihan from './MultimediaPilihan';

const MultimediaMain = () => {
    return (
        <>
            <Head>
                <title>Multimedia - Sociesmedia</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <UserLayout>
                <MultimediaHero />
                <MultimediaPilihan/>
                <a 
                    href="#"
                    className="fixed bottom-5 right-5 bg-black text-white p-3 rounded-lg shadow-lg text-center"
                    style={{ width: '80px', height: '80px' }}
                >
                    <div className="text-xs">Kelola</div>
                    <div className="font-semibold">Media</div>
                </a>
            </UserLayout>
        </>
    );
};

export default MultimediaMain;
