import React from 'react';
import UserLayout from "@/Layout/UserLayout.jsx";
import { Button } from "@/Components/ui/button.jsx"
import {Head} from "@inertiajs/react";
import MultimediaHero from "@/Pages/User/Multimedia/MultimediaHero.jsx";
import MultimediaPilihan from './MultimediaPilihan';

const MultimediaMain = () => {
    return (
        <>
            <Head>
                <title>Multimedia - Sociesmedia</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <UserLayout>
                <MultimediaHero />
                <MultimediaPilihan/>
            </UserLayout>
        </>
    );
};

export default MultimediaMain;
