import React from 'react';
import UserLayout from "@/Layout/UserLayout.jsx";

import {Input, Card, CardHeader, CardBody, CardFooter, Image, Button} from "@nextui-org/react";

import {Head} from "@inertiajs/react";
import ArtikelHero from './ArtikelHero';
import ArtikelPilihan from './ArtikelPilihan';

const ArtikelMain = () => {
    return (
        <>
            <Head>
                <title>Beranda - Sociesmedia</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <UserLayout>
               <ArtikelHero/>
               <ArtikelPilihan/>
        </UserLayout>
        </>
    );
};

export default ArtikelMain;
