import UserLayout from '@/Layout/UserLayout'
import { Head } from '@inertiajs/react'
import React from 'react'
import ProfileHero from './ProfileHero'

const ProfileMain = () => {
  return (
    <>
        <Head>
            <title>Profile - Sociesmedia</title>
            <meta name="description" content="Generated by create next app"/>
        </Head>

        <UserLayout>
            <ProfileHero  />
        </UserLayout>
    </>
  )
}

export default ProfileMain