import React from 'react';
import UserLayout from "@/Layout/UserLayout.jsx";
import MateriHero from "@/Pages/User/Materi/MateriHero.jsx";
import { Head } from "@inertiajs/react";
import MateriPilihan from './MateriPilihan';

const MateriMain = () => {
    return (
        <>
            <Head>
                <title>Materi - Sociesmedia</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <UserLayout>
                <MateriHero />
                <MateriPilihan />

                <a 
                    href="#"
                    className="fixed bottom-5 right-5 bg-black text-white p-3 rounded-lg shadow-lg text-center"
                    style={{ width: '80px', height: '80px' }}
                >
                    <div className="text-xs">Kelola</div>
                    <div className="font-semibold">Materi</div>
                </a>
            </UserLayout>
        </>
    );
};

export default MateriMain;
