import React from 'react';
import UserLayout from "@/Layout/UserLayout.jsx";
import MateriHero from "@/Pages/User/Materi/MateriHero.jsx";
import {Head} from "@inertiajs/react";
import MateriPilihan from './MateriPilihan';

const MateriMain = () => {
    return (
        <>
            <Head>
                <title>Materi - Sociesmedia</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <UserLayout>
                <MateriHero/>
                <MateriPilihan/>
            </UserLayout>
        </>
    );
};

export default MateriMain;
